name: Prettier Check

on: 
  push:
    branches:
      - "*"

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm ci

      - name: Check formatting
        run: npx prettier --check "**/*.{js,ts,tsx}"        
