name: Prettier Check

on: [push]

permissions:
  contents: write

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm ci

      - name: Format Code
        run: npx prettier --write .

      - name: Commit Changes
        run: |
          git config user.name "Jan Čelovský"
          git config user.email "celovskyhonza@gmail.com"
          git add .
          git commit -m "Format code using Prettier"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
